import type { VocabEntry } from './types';

const now = new Date();
const due = new Date(now.getTime() - 60_000).toISOString();

export const sampleWords: VocabEntry[] = [
  { id:'1', headword:'sustainable', ipa:'/səˈsteɪ.nə.bəl/', partOfSpeech:'ADJECTIVE', meaningVi:'bền vững', definitionEn:'able to continue over a long period of time', exampleEn:'Governments should promote sustainable development.', exampleVi:'Chính phủ nên thúc đẩy phát triển bền vững.', topic:'Environment', level:'B2', entryType:'WORD', synonyms:['viable','long-term'], wordFamily:['sustain (v)','sustainability (n)','sustainably (adv)'], createdAt:now.toISOString(), intervalDays:1, nextReviewAt:due, correctCount:4, wrongCount:1 },
  { id:'2', headword:'deteriorate', ipa:'/dɪˈtɪə.ri.ə.reɪt/', partOfSpeech:'VERB', meaningVi:'suy giảm; trở nên tồi tệ hơn', definitionEn:'to become worse', exampleEn:'Air quality has deteriorated significantly in recent years.', exampleVi:'Chất lượng không khí đã suy giảm đáng kể trong những năm gần đây.', topic:'Environment', level:'C1', entryType:'WORD', synonyms:['worsen','decline'], wordFamily:['deterioration (n)'], createdAt:now.toISOString(), intervalDays:1, nextReviewAt:due, correctCount:2, wrongCount:3 },
  { id:'3', headword:'expenditure', ipa:'/ɪkˈspen.dɪ.tʃər/', partOfSpeech:'NOUN', meaningVi:'chi tiêu; khoản chi', definitionEn:'the act of spending money', exampleEn:'Government expenditure on education has increased.', topic:'Economy', level:'C1', entryType:'WORD', synonyms:['spending'], wordFamily:['expend (v)'], createdAt:now.toISOString(), intervalDays:3, nextReviewAt:due, correctCount:3, wrongCount:2 },
  { id:'4', headword:'inevitable', ipa:'/ɪˈnev.ɪ.tə.bəl/', partOfSpeech:'ADJECTIVE', meaningVi:'không thể tránh khỏi', definitionEn:'certain to happen and unable to be avoided', exampleEn:'Technological change is inevitable.', topic:'Technology', level:'C1', entryType:'WORD', synonyms:['unavoidable'], wordFamily:['inevitably (adv)','inevitability (n)'], createdAt:now.toISOString(), intervalDays:7, nextReviewAt:due, correctCount:7, wrongCount:1 },
  { id:'5', headword:'carry out', ipa:'', partOfSpeech:'PHRASAL_VERB', meaningVi:'thực hiện, tiến hành', definitionEn:'to perform or complete an activity', exampleEn:'Researchers carried out a large-scale experiment.', topic:'Academic', level:'B2', entryType:'PHRASAL_VERB', synonyms:['conduct','perform'], wordFamily:[], createdAt:now.toISOString(), intervalDays:1, nextReviewAt:due, correctCount:4, wrongCount:2 },
  { id:'6', headword:'account for', ipa:'', partOfSpeech:'PHRASAL_VERB', meaningVi:'chiếm; giải thích cho', definitionEn:'to form a particular amount or explain something', exampleEn:'Transport accounts for a large share of urban emissions.', topic:'Academic', level:'C1', entryType:'PHRASAL_VERB', synonyms:['constitute','explain'], wordFamily:[], createdAt:now.toISOString(), intervalDays:1, nextReviewAt:due, correctCount:2, wrongCount:4 }
];
